plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://reasoning-machine.github.io
baseurl: /openai

title: Reasoning Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Reasoning-Machine
  instructions_file: reasoning.txt
  token: openai.txt
  apiUrl: https://api.openai.com/v1/chat/completions

app:
  worker_name: oaiapi.js

lm:
  model: gpt-5
  max_tokens: 8192
  presence_penalty: 0.0
  frequency_penalty: 0.0
  temperature: 1.0
  top_p: 0.95

github_settings:
  owner: reasoning-machine
  repo: reasoning_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
